*** Variables ***
${FIRSTNAME.TXT}    id=customer.firstName
${LASTNAME.TXT}     id=customer.lastName
${ADDRESS.TXT}      id=customer.address.street
${CITY.TXT}         id=customer.address.city
${STATE.TXT}        id=customer.address.state
${ZIPCODE.TXT}      id=customer.address.zipCode
${PHONE.TXT}        id=customer.phoneNumber
${SSN.TXT}          id=customer.ssn
${CONFIRMPASS.TXT}  id=repeatedPassword
${REGISTER.BTN}     //input[@value="Register"]